# agents/beamer_agent.py (NEW FILE)

def beamer_agent(state):
    data = state["presentation"]
    slides = data["slides"]
    
    # 1. Beamer Header
    latex_code = r"""
\documentclass{beamer}
\usetheme{Madrid}
\usecolortheme{dolphin}
\usepackage{graphicx}
\usepackage{amsmath}

\title{""" + data.get("title", "Research Presentation") + r"""}
\author{Generated by Agent}
\date{\today}

\begin{document}

\frame{\titlepage}
"""

    # 2. Loop through slides
    for slide in slides:
        title = slide["title"]
        # Escape special LaTeX characters if needed, for simple text we assume clean input
        content = slide.get("content", "")
        bullets = "\n".join([f"    \\item {bp}" for bp in slide.get("key_points", [])])
        
        # Slide Structure
        slide_block = f"""
\\begin{{frame}}[shrink]{{{title}}}
    \\begin{{columns}}
        \\column{{0.6\\textwidth}}
        {content}
        \\vspace{{0.5cm}}
        \\begin{{itemize}}
        {bullets}
        \\end{{itemize}}

        \\column{{0.4\\textwidth}}
        \\centering
        % Placeholder for image - in a real agent, we would download the AI image and include it
        % \\includegraphics[width=\\textwidth]{{image.png}}
        \\textit{{[Visual: {slide.get('visual_description', 'Diagram')}]}}
    \\end{{columns}}
\\end{{frame}}
"""
        latex_code += slide_block

    # 3. Footer
    latex_code += r"\end{document}"

    # 4. Save to file
    with open("presentation.tex", "w") as f:
        f.write(latex_code)
    
    return state